### ISSUE TITLE
AddChannel()

### ISSUE THREAD

**Issue by Dale-Black** [lorenzoh/DataAugmentation.jl#25]
Hey. Just wanted to see if there is any reason not to have `AddChannel()` as part of the transforms? I know its simple to write on your own but it might be nice to have regardless. Anything I am missing?

    # ### ['AddChannel']
    """
        AddChannel()
    Adds a channel for grayscale images
    """
    struct AddChannel <: Transform end
    
    function apply(tfm::AddChannel, item::Image; randstate = nothing)
        array = itemdata(item)
        array = reshape(array, size(array)..., 1)
        return Image(array)
    end
    
    function apply(tfm::AddChannel, item::MaskBinary; randstate = nothing)
        array = itemdata(item)
        array = reshape(array, size(array)..., 1)
        return Image(array)
    end

**Comment by lorenzoh** [comment]
See #22
