### ISSUE TITLE
Random state argument for consistent random augmentations

### ISSUE THREAD

**Issue by Dale-Black** [lorenzoh/DataAugmentation.jl#47]
I would like to suggest an argument for `RandomResizeCrop` and other stochastic transformations. Something like `RandomResizeCrop(seed=...)` would be really convenient for augmenting supervised data with the same random seed. This isn't necessary obviously as you have already given me a helpful workaround, but in case this is easy to implement I wanted to add this suggestion

**Comment by lorenzoh** [comment]
So you want to fix the randomness of a stochastic transformation so it always gives the same result? What would `seed` do exactly?

**Comment by Dale-Black** [comment]
I was thinking something like [this](https://www.tensorflow.org/tutorials/images/data_augmentation). But I’m not sure if this is much cleaner than the route you have already proposed actually

**Comment by lorenzoh** [comment]
Hm, I don't really see an advantage in this. One thing to do could be to implement a wrapper transform `Deterministic` that wraps a transform and always passes the same random state through. That way you wouldn't need to change existing transforms.

**Comment by Dale-Black** [comment]
Fair enough. I think I agree with you the more I think about it
