### ISSUE TITLE
RandomCrop transform msssing one offset position

### ISSUE THREAD

**Issue by donlzx** [lorenzoh/DataAugmentation.jl#68]
RandomCrop returns uneven cropping for small images (e.g. MNIST and CIFAR-10/100), thus yielding sub-optimal performance in training.
 
For example, cropping 32x32 images from 36x36 images should have bound offsets [0, 1, 2, 3, 4].  However, currently only [0, 1, 2, 3] is used.

Here are 20 images generated using RandomCrop with DataAugmentation v0.2.8. The original images (32x32 in size) are padded by 2 pixels on each edge, randomly cropped to 32x32, and then up-sampled to 128x128 for display.

The left and top edges of the images are randomly padded by either 0/1/2 pixels, while the right edges are only paded by 0/1 pixels.

![randcrop_before](https://user-images.githubusercontent.com/10166292/174414388-68b869e8-db93-451b-a7bd-3a0f28418fe6.png)

**Comment by lorenzoh** [comment]
Thanks for reporting this! I don't have the time right now myself, unfortunately, but I'd be happy to review a pull request.

**Comment by lorenzoh** [comment]
Closed by #69
