### ISSUE TITLE
docs issue

### ISSUE THREAD

**Issue by CarloLucibello** [lorenzoh/DataAugmentation.jl#71]
The output in this page is not quite readable
https://lorenzoh.github.io/DataAugmentation.jl/dev/REFERENCE/DataAugmentation.Image.html

Also, the second example mentions a greyscale image that cannot be seen in the output

**Comment by lorenzoh** [comment]
Try https://lorenzoh.github.io/DataAugmentation.jl/dev/references/DataAugmentation.Image

I updated the link in the README, the one you had was pointing to the old documentation, I forgot to update it when switching to the new Pollen.jl frontend
