### ISSUE TITLE
AdjustBrightness and AdjustContrast without clamp01

### ISSUE THREAD

**Issue by itan1** [lorenzoh/DataAugmentation.jl#76]
Currently the output images are clamped with `clamp01` in AdjustBrightness  ([here](https://github.com/lorenzoh/DataAugmentation.jl/blob/master/src/colortransforms.jl#L55)) and AdjustContrast ([here](https://github.com/lorenzoh/DataAugmentation.jl/blob/master/src/colortransforms.jl#L115)).

I am working with medical data with a different grayscale range than [0,1] so I would like to use the augmentation methods but without clamping. Was there a specific reason to use the clamping? Can I add an optional clamp flag like below?

```julia
function adjustcontrast!(dst::AbstractArray{U}, img::AbstractArray{T}, factor; clamp=true) where {T, U}
    map!(dst, img) do x
        convert(U, clamp ? clamp01(x * factor) : x * factor)
    end
end
```

**Comment by lorenzoh** [comment]
The reason for the default clamping is that the default low-memory color type is `RGB{N0f8}` which is represented under the hood as `UInt8`s. When trying to convert a number outside the inveral `[0, 1]` back to that representation, an error is thrown.

Happy to accept a PR adding the `clamp = true` flag for `AdjustBrightness` and `AdjustContrast` :)
