### ISSUE TITLE
Registration of DataAugmentation `v0.3` failed

### ISSUE THREAD

**Issue by adrhill** [lorenzoh/DataAugmentation.jl#96]
The last two registrations for DataAugmentations [`v0.3.1`](https://github.com/JuliaRegistries/General/pull/111467#issuecomment-2241773417) and [`v0.3.2`](https://github.com/JuliaRegistries/General/pull/113610#issuecomment-2302681237) failed since `v0.3.0` was skipped over.

The last registered release is still `v0.2.12`.

**Comment by adrhill** [comment]
Bump @CarloLucibello @darsnack

**Comment by CarloLucibello** [comment]
I'm registering v0.3.0 
https://github.com/JuliaRegistries/General/pull/114561
